### ISSUE TITLE
[BUG]: Crash when stopped recording

### ISSUE THREAD

**Issue by jimmywim** [microsoft/m365-developer-proxy#284]
### Description

Got a crash out when stopping recording (pressing `s` during a record session with the proxy running)

### Expected behaviour

Recording to stop, any plugins to report any output from the recorded session.

### Actual behaviour

```
○ Stopped recording
An error occurred while running the Developer Proxy
The given key 'GET https://REDACTED.sharepoint.com/sites/REDACTED/_api/web/lists/getByTitle('REDACTED')/items?$select=Id%2CTitle%2CREDACTEDFIELDNAME%2CREDACTEDFIELDNAME%2CREDACTEDFIELDNAME%2CREDACTEDFIELDNAME%2CModified%2CCreated&$filter=REDACTEDFIELDNAME eq 1&$orderby=Modified desc' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft365.DeveloperProxy.Plugins.RequestLogs.ExecutionSummaryPlugin.GetGroupedByUrlData(IEnumerable`1 requestLogs)
   at Microsoft365.DeveloperProxy.Plugins.RequestLogs.ExecutionSummaryPlugin.GetGroupedByUrlReport(IEnumerable`1 requestLogs)
   at Microsoft365.DeveloperProxy.Plugins.RequestLogs.ExecutionSummaryPlugin.AfterRecordingStop(Object sender, RecordingArgs e)
   at Microsoft365.DeveloperProxy.Abstractions.PluginEvents.RaiseRecordingStopped(RecordingArgs args)
   at Microsoft365.DeveloperProxy.ProxyEngine.StopRecording()
   at Microsoft365.DeveloperProxy.ProxyEngine.ReadKeys()
   at Microsoft365.DeveloperProxy.ProxyEngine.Run(Nullable`1 cancellationToken)
   at Microsoft365.DeveloperProxy.ProxyCommandHandler.InvokeAsync(InvocationContext context)
```

### Steps to reproduce

Not sure how to reproduce outside of our product (with a lot of graph-consuming web parts on - we're looking to optimise, hence this tool!)

However, I believe the request in the "Actual behaviour" output, with the List OData request may be enough to trigger it.

### Microsoft 365 Developer Proxy Version

0.9.0

### Operating system (environment)

Windows

### Shell

Windows PowerShell

### Additional Info

Enabled Plugins:
default, and:

- ExecutionSummaryPlugin
- MinimalPermissionsGuidancePlugin

**Comment by waldekmastykarz** [comment]
Thank you for reporting this and sorry for the snag. We'll investigate asap.

**Comment by waldekmastykarz** [comment]
The issue was caused by a discrepancy in the host name: while we originally capture the host name of the request as-is, later down the pipe, one of our dependencies changes it to lowercase which is why the reference to the dictionary was failing with an exception. We've changed the logic to always take the URL from the dependency to ensure that they're compared consistently.
