### ISSUE TITLE
[Feature Proposal] Insert lower-level connection errors

### ISSUE THREAD

**Issue by heinrich-ulbricht** [microsoft/m365-developer-proxy#296]
I'd like to simulate connection failures and did not find any documentation if this can be done.

This is something I'd like to be able to spray randomly into all connections:

```
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
```

**Comment by waldekmastykarz** [comment]
Thanks for the suggestion, @heinrich-ulbricht. We'll have a look at what's possible

**Comment by heinrich-ulbricht** [comment]
@waldekmastykarz That would be great. Had a nasty case where those kept happening every 30 seconds or so. They require a different level of retry logic since the entire connection is gone and there is no HTTP status code to look at.

**Comment by waldekmastykarz** [comment]
> @waldekmastykarz That would be great. Had a nasty case where those kept happening every 30 seconds or so. They require a different level of retry logic since the entire connection is gone and there is no HTTP status code to look at.

Thank you for the additional clarification. The elusive character of these errors sounds like a perfect match for the proxy.

**Comment by waldekmastykarz** [comment]
From @johnknoop in #1136:

> This tool is really handy! I was just wondering... today it can only simulate HTTP errors, where the remote machine would actually return an HTTP status code. Would it be possible to simulate stuff like dropped connections, network timeouts, DNS errors etc? Because it's typically those kinds of errors that are regarded as transient, meaning many applications will have different retry policies for those errors compared to HTTP-level errors.

We looked into it at some point but haven't found an easy way to simulate these behaviors using our current proxy implementation. Totally open to revisit if we can find a way for it. I still believe that this would be a great addition.
